Add Assumed Identity examples - Adds Assumed Identity to each example - Adds new tests to demonstrate POC with the DefaultAzureCredential - Updates documentation - Updates version bump scripts to handle both Lowkey Vault and Assumed Identity version changes using the same approach
Signed-off-by: Esta Nagy <nagyesta@gmail.com>

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -17,7 +17,7 @@ jobs:
             name: Docker with a shell script
             path: docker
             tool: docker
-            stop: docker stop lowkey-docker
+            stop: docker stop lowkey-docker assumed-id-docker
           - module: compose
             name: Docker Compose with the classic image
             path: docker-compose
@@ -43,6 +43,7 @@ jobs:
         docker-compose up -d
         sleep 5
         docker ps
+        if [ $(docker ps | grep nagyesta | wc -l) -ne 2 ]; then echo "ERROR: Some containers are not running"; exit 1; fi
     - name: Start Lowkey Vault using Docker command
       if: ${{ matrix.tool == 'docker' }}
       run: |
@@ -51,7 +52,11 @@ jobs:
         sh example.sh
         sleep 5
         docker ps
+        if [ $(docker ps | grep nagyesta | wc -l) -ne 2 ]; then echo "ERROR: Some containers are not running"; exit 1; fi
     - name: Test with go
+      env:
+        IDENTITY_ENDPOINT: http://localhost:8080/metadata/identity/oauth2/token
+        IDENTITY_HEADER: header
       run: |
         go clean -testcache
         go test ./test -v
